// <auto-generated />
using HamsterWarz.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamsterWarz.Server.Migrations
{
    [DbContext(typeof(HamsterWarzContext))]
    [Migration("20220602200833_6")]
    partial class _6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamsterWarz.Shared.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 12,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "hamster-1.jpg",
                            Losses = 0,
                            Loves = "Gaming",
                            Name = "Samuel",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            FavFood = "Burgers",
                            Games = 0,
                            ImgName = "hamster-2.jpg",
                            Losses = 0,
                            Loves = "Elden Ring",
                            Name = "Jonathan",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 44,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "hamster-3.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Elias",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 12,
                            FavFood = "Broccoli",
                            Games = 0,
                            ImgName = "hamster-4.jpg",
                            Losses = 0,
                            Loves = "Sports",
                            Name = "Johan",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 100,
                            FavFood = "Shrimp",
                            Games = 0,
                            ImgName = "hamster-5.jpg",
                            Losses = 0,
                            Loves = "Tacos",
                            Name = "Patrik",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 30,
                            FavFood = "HotDogs",
                            Games = 0,
                            ImgName = "hamster-6.jpg",
                            Losses = 0,
                            Loves = "Nothing",
                            Name = "Sofia",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 10,
                            FavFood = "Cheese",
                            Games = 0,
                            ImgName = "hamster-7.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Patricia",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 33,
                            FavFood = "Kebab",
                            Games = 0,
                            ImgName = "hamster-8.jpg",
                            Losses = 0,
                            Loves = "Nothing",
                            Name = "Britta",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 100,
                            FavFood = "Shrimp",
                            Games = 0,
                            ImgName = "hamster-9.jpg",
                            Losses = 0,
                            Loves = "Tacos",
                            Name = "Patrik",
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            Age = 12,
                            FavFood = "Shrimp",
                            Games = 0,
                            ImgName = "hamster-10.jpg",
                            Losses = 0,
                            Loves = "Music",
                            Name = "Marshall",
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            Age = 13,
                            FavFood = "Cucumber",
                            Games = 0,
                            ImgName = "hamster-11.jpg",
                            Losses = 0,
                            Loves = "Programming",
                            Name = "Greta",
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            Age = 15,
                            FavFood = "Nachos",
                            Games = 0,
                            ImgName = "hamster-12.jpg",
                            Losses = 0,
                            Loves = "Beer",
                            Name = "FrankTheTank",
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            Age = 13,
                            FavFood = "Carrots",
                            Games = 0,
                            ImgName = "hamster-13.jpg",
                            Losses = 0,
                            Loves = "Dancing",
                            Name = "Hammy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            Age = 11,
                            FavFood = "Rice",
                            Games = 0,
                            ImgName = "hamster-14.jpg",
                            Losses = 0,
                            Loves = "Party",
                            Name = "FlipFlop",
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            Age = 2,
                            FavFood = "Falafel",
                            Games = 0,
                            ImgName = "hamster-15.jpg",
                            Losses = 0,
                            Loves = "Dancing",
                            Name = "Mohammed",
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            Age = 37,
                            FavFood = "Kebabtallrik",
                            Games = 0,
                            ImgName = "hamster-16.jpg",
                            Losses = 0,
                            Loves = "Bowling",
                            Name = "Adam",
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            Age = 2,
                            FavFood = "Vegetables",
                            Games = 0,
                            ImgName = "hamster-17.jpg",
                            Losses = 0,
                            Loves = "Formula1",
                            Name = "Johanna",
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            Age = 22,
                            FavFood = "Candy",
                            Games = 0,
                            ImgName = "hamster-18.jpg",
                            Losses = 0,
                            Loves = "Kanelbullar",
                            Name = "Gerda",
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            Age = 18,
                            FavFood = "Sushi",
                            Games = 0,
                            ImgName = "hamster-19.jpg",
                            Losses = 0,
                            Loves = "Dancing",
                            Name = "Helen",
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            Age = 14,
                            FavFood = "Burgers",
                            Games = 0,
                            ImgName = "hamster-20.jpg",
                            Losses = 0,
                            Loves = "Beer",
                            Name = "Totte",
                            Wins = 0
                        },
                        new
                        {
                            Id = 21,
                            Age = 2,
                            FavFood = "Apple",
                            Games = 0,
                            ImgName = "hamster-21.jpg",
                            Losses = 0,
                            Loves = "Movies",
                            Name = "IPhone",
                            Wins = 0
                        },
                        new
                        {
                            Id = 22,
                            Age = 7,
                            FavFood = "Mentos",
                            Games = 0,
                            ImgName = "hamster-22.jpg",
                            Losses = 0,
                            Loves = "Bubbles",
                            Name = "Coke",
                            Wins = 0
                        },
                        new
                        {
                            Id = 23,
                            Age = 49,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "hamster-23.jpg",
                            Losses = 0,
                            Loves = "Fighting",
                            Name = "Blanca",
                            Wins = 0
                        },
                        new
                        {
                            Id = 24,
                            Age = 66,
                            FavFood = "BiffRydberg",
                            Games = 0,
                            ImgName = "hamster-24.jpg",
                            Losses = 0,
                            Loves = "Music",
                            Name = "Jethro",
                            Wins = 0
                        },
                        new
                        {
                            Id = 25,
                            Age = 4,
                            FavFood = "BeefTartar",
                            Games = 0,
                            ImgName = "hamster-25.jpg",
                            Losses = 0,
                            Loves = "Women",
                            Name = "SamTheMan",
                            Wins = 0
                        },
                        new
                        {
                            Id = 26,
                            Age = 42,
                            FavFood = "Italian",
                            Games = 0,
                            ImgName = "hamster-26.jpg",
                            Losses = 0,
                            Loves = "Family",
                            Name = "Vinnie",
                            Wins = 0
                        },
                        new
                        {
                            Id = 27,
                            Age = 20,
                            FavFood = "Meat",
                            Games = 0,
                            ImgName = "hamster-27.jpg",
                            Losses = 0,
                            Loves = "People",
                            Name = "Dexter",
                            Wins = 0
                        },
                        new
                        {
                            Id = 28,
                            Age = 22,
                            FavFood = "Salad",
                            Games = 0,
                            ImgName = "hamster-28.jpg",
                            Losses = 0,
                            Loves = "Barbie",
                            Name = "Ken",
                            Wins = 0
                        },
                        new
                        {
                            Id = 29,
                            Age = 39,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "hamster-29.jpg",
                            Losses = 0,
                            Loves = "Amber Heard",
                            Name = "Johnny",
                            Wins = 0
                        },
                        new
                        {
                            Id = 30,
                            Age = 9,
                            FavFood = "PadThai",
                            Games = 0,
                            ImgName = "hamster-30.jpg",
                            Losses = 0,
                            Loves = "Gaming",
                            Name = "Linus",
                            Wins = 0
                        },
                        new
                        {
                            Id = 31,
                            Age = 13,
                            FavFood = "PyttiPanna",
                            Games = 0,
                            ImgName = "hamster-31.jpg",
                            Losses = 0,
                            Loves = "Robin",
                            Name = "Batman",
                            Wins = 0
                        },
                        new
                        {
                            Id = 32,
                            Age = 11,
                            FavFood = "Carrots",
                            Games = 0,
                            ImgName = "hamster-32.jpg",
                            Losses = 0,
                            Loves = "Batman",
                            Name = "Joker",
                            Wins = 0
                        },
                        new
                        {
                            Id = 33,
                            Age = 55,
                            FavFood = "FriedRice",
                            Games = 0,
                            ImgName = "hamster-33.jpg",
                            Losses = 0,
                            Loves = "Soda",
                            Name = "Biro",
                            Wins = 0
                        },
                        new
                        {
                            Id = 34,
                            Age = 9,
                            FavFood = "Waffles",
                            Games = 0,
                            ImgName = "hamster-34.jpg",
                            Losses = 0,
                            Loves = "Cars",
                            Name = "Urkel",
                            Wins = 0
                        },
                        new
                        {
                            Id = 35,
                            Age = 4,
                            FavFood = "Snake",
                            Games = 0,
                            ImgName = "hamster-35.jpg",
                            Losses = 0,
                            Loves = "Explosions",
                            Name = "Rambo",
                            Wins = 0
                        },
                        new
                        {
                            Id = 36,
                            Age = 1,
                            FavFood = "Worms",
                            Games = 0,
                            ImgName = "hamster-36.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Jim",
                            Wins = 0
                        },
                        new
                        {
                            Id = 37,
                            Age = 30,
                            FavFood = "Sandwiches",
                            Games = 0,
                            ImgName = "hamster-37.jpg",
                            Losses = 0,
                            Loves = "Rachel",
                            Name = "Ross",
                            Wins = 0
                        },
                        new
                        {
                            Id = 38,
                            Age = 11,
                            FavFood = "Spaghetti",
                            Games = 0,
                            ImgName = "hamster-38.jpg",
                            Losses = 0,
                            Loves = "Computers",
                            Name = "Blazor",
                            Wins = 0
                        },
                        new
                        {
                            Id = 39,
                            Age = 10,
                            FavFood = "Lasagna",
                            Games = 0,
                            ImgName = "hamster-39.jpg",
                            Losses = 0,
                            Loves = "Women",
                            Name = "Joey",
                            Wins = 0
                        },
                        new
                        {
                            Id = 40,
                            Age = 21,
                            FavFood = "Cryptonite",
                            Games = 0,
                            ImgName = "hamster-40.jpg",
                            Losses = 0,
                            Loves = "Lois",
                            Name = "Clark",
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
